### ISSUE TITLE
Finder 4.x docs claim the find($mask) is optional

### ISSUE THREAD

**Issue by finwe** [nette/docs#1012]
Version: utils 4.0.0, finder 3.0.0

### Bug Description
[Finder 4.x docs](https://doc.nette.org/en/utils/finder#toc-what-to-search-for) claim the `find($mask)` parameter is optional, but it is typed as `string|array` with no default value. The code example also shows call of `find()` without a parameter.

### Steps To Reproduce
Try to call `Finder::find()`, a missing parameter error is thrown

### Possible Solution
The default value is added to the `find()` method (as well as `findFiles` and `findDirectories`), or the documentation is changed accordingly.

I'll be happy to prepare a PR, I just need to know which solution is the preferred one.

**Comment by dg** [comment]
Fixed in utils 4.0.1
