### ISSUE TITLE
Make it simpler

### ISSUE THREAD

**Issue by reubenalfred** [nette/docs#1047]
URL: https://doc.nette.org/en/application/how-it-works

Hi guys,

thank you for this beautiful framework and your hard work, it is very much appreciated!!

IMHO, the information on this page has to be simplified without any framework related entities or the files and directories. It is fair to introduce the directory structure and introduce the concepts but explain them in general terms because the subsequent sections elaborate on the terms introduced.

i kept reading this page over and over again and then out of frustration and moved to the next page and the 4 lines of code just made it far too easy to explain the what the 1st half of this page tried to do with the words.

Kind Regards,

reuben

**Comment by dg** [comment]
Hey, Reuben,

I'd be happy to improve the page, but I'd need to know specifically what you found incomprehensible and what helped you understand the documentation. Which concepts you don't find general. 

If you feel like it, feel free to try using ChatGPT to suggest a better form.

Thanks
