### ISSUE TITLE
Tracy: detekce vývojového řežimu na základě cookies

### ISSUE THREAD

**Issue by JanTvrdik** [nette/docs#201]
Debugger::enable() implements checking of cookie (format cookie@ip.address)

**Comment by f3l1x** [comment]
Already in: 

![selection_021](https://user-images.githubusercontent.com/538058/27626958-4d5850f8-5bea-11e7-9f1d-91a1caa9de49.png)

![selection_020](https://user-images.githubusercontent.com/538058/27626955-4ad6b252-5bea-11e7-8e0b-0c33c5661310.png)
