### ISSUE TITLE
Database: vyhazuje vlastní výjimky

### ISSUE THREAD

**Issue by medhi** [nette/docs#210]
throws own exceptions:
DriverException, ConnectionException
ConstraintViolationException, ForeignKeyConstraintViolationException,NotNullConstraintViolationException and UniqueConstraintViolationException

**Comment by f3l1x** [comment]
It's already mentioned: 

- https://doc.nette.org/cs/2.4/database-core#toc-insert-update-delete
- https://doc.nette.org/en/2.4/database-core#toc-insert-update-delete
