### ISSUE TITLE
Application: removed case insensitivity for presenters and actions

### ISSUE THREAD

**Issue by klimesf** [nette/docs#211]

**Comment by f3l1x** [comment]
@dg At koukam, jak koukam, v dokumentaci jsem nic nenasel. Ze by to uz nebylo relevantni? :-)

**Comment by f3l1x** [comment]
Napada te @dg k tomu neco? Porad nemuzu prijit na to oc jde.

**Comment by dg** [comment]
Nevim čéče

**Comment by f3l1x** [comment]
@klimesf Muzes nam trochu pomoci/poradit? :-)

**Comment by f3l1x** [comment]
Napsal jsem mu radeji jeste mail, nez to zavreme.

**Comment by f3l1x** [comment]
I'm closing it now. Feel free to open it with more providing more information. Thanks @klimesf.
