### ISSUE TITLE
Utils: add documentation for Arrays::normalize(), Callback::invokeSafe(), Html::data(),

### ISSUE THREAD

**Issue by chemix** [nette/docs#213]
- [x] Arrays::normalize http://api.nette.org/2.3.0/source-Utils.Arrays.php.html#226-237

- [ ] Callback::invokeSafe() http://api.nette.org/2.3.0/source-Utils.Callback.php.html#82-106

- [x] Html::data() http://api.nette.org/2.3.0/source-Utils.Html.php.html#234-246

**Comment by f3l1x** [comment]
- Html::data() - https://doc.nette.org/cs/2.4/html-elements

V HTML 5 lze používat tzv. datové atributy pro uživatelská data:

<img src="img.jpg" data-max-size="500x300" />
Obvykle pak hodnoty těchto atributů využívá JavaScript. A fungují ve všech prohlížečích.

Třída Html disponuje přímou podporou pro datové atributy z HTML5:

$el = Html::el('img');
$el->data['max-size'] = '500x300';
// nebo
$el->data('max-size', '500x300');

**Comment by dg** [comment]
`$el->data['max-size'] = '500x300';` is deprecated

**Comment by dg** [comment]
Ona není vůbec zdokumentovaná třída `Callback`. Zrovna metodu `invokeSafe` dokumentovat asi není potřeba, protože je v podstatě interní.

**Comment by chemix** [comment]
@dg tak pridat do kodu @internal ?

**Comment by f3l1x** [comment]
Zalozil jsem novy ticket jenom na Callback, at v tom mame poradek. 

https://github.com/nette/docs/issues/602
