### ISSUE TITLE
Application: Router caching + action name can begin with number

### ISSUE THREAD

**Issue by klimesf** [nette/docs#215]

**Comment by f3l1x** [comment]
@dg Cachovani rout jsem zatim ani jednou nepouzil, tak se tesim, az to testu kvuli docce. Nejake tipy na co se zamerit?

**Comment by dg** [comment]
Zapina se to v konfigu:

```
routing:
    cache: yes
```

a jde o to, že se objekt routeru serializuje, takže nemůže obsahovat callbacky nebo vazby na jine objekty, například v Route::FILTER_IN a Route::FILTER_OUT.

**Comment by f3l1x** [comment]
Diky moc :-)

**Comment by f3l1x** [comment]
Hell ya, done. :smiley:
