### ISSUE TITLE
Database: nové operátory a značky

### ISSUE THREAD

**Issue by medhi** [nette/docs#216]
- [x] added support for += and -= in UPDATE statement
- [x] added support for operators in WHERE & AND
- [x] implemented ?and ?or ?set ?values ?order ?name
- [x] added support for ‘.’ in column names

**Comment by f3l1x** [comment]
Adding anchors:

- https://github.com/nette/database/blob/master/tests/Database/SqlPreprocessor.phpt#L452
- https://github.com/nette/database/blob/master/tests/Database/SqlPreprocessor.phpt#L429
- https://github.com/nette/database/blob/master/tests/Database/SqlPreprocessor.phpt#L398

**Comment by f3l1x** [comment]
@dg Do jake stranky by jsi hodil tyhle operatory?

**Comment by dg** [comment]
Určitě Core.

**Comment by f3l1x** [comment]
Super ;-)
