### ISSUE TITLE
DI: service aliases

### ISSUE THREAD

**Issue by klimesf** [nette/docs#222]

**Comment by f3l1x** [comment]
Tim je mysleno:

```php
$builder->addAlias(x, y)
```

WDYT @dg?

**Comment by f3l1x** [comment]
Lze alias vytvorit i jinak?

**Comment by dg** [comment]
Jen přes builder. V ale v neonu jde dělat jakoalias `alias: @anotherservice`

**Comment by f3l1x** [comment]
> Pokud potrebujete kvuli zachovani zpetne kompatibilite prejmenovat sluzbu, muzete vytvorit alias..
