### ISSUE TITLE
DI: zdokumentovat DecoratorExtension, DIExtension a InjectExtension

### ISSUE THREAD

**Issue by klimesf** [nette/docs#224]

**Comment by f3l1x** [comment]
@dg Kdyz tedka mame sekci Dependecy Injection, spada Decorator, DI a Inject Extension do nejake stranky? Nebo vytvorime nejakou Default Extensions?

**Comment by dg** [comment]
A ještě ExtensionsExtension.

Asi nějaké di-defaultextensions by to chtělo. Zároveň by bylo dobré jen s odkazem zmínit v configuring.

**Comment by f3l1x** [comment]
Closed via #611
