### ISSUE TITLE
DI: zdokumentovat CompilerExtension::validateConfig()

### ISSUE THREAD

**Issue by klimesf** [nette/docs#226]

**Comment by f3l1x** [comment]
Uvedl bych to tady: https://doc.nette.org/cs/2.4/di-extensions#toc-loadconfiguration

```php
class MyBlogExtension extends Nette\DI\CompilerExtension
{
    public $defaults = [
        'postsPerPage' => 5,
        'comments' => true
    ];

    public function loadConfiguration()
    {
        $this->config += $this->defaults;
// $config = $this->validateConfig($this->defaults);
```

S tim, ze validateConfig (https://api.nette.org/2.4/source-DI.CompilerExtension.php.html#69-81) vlastne vezme hodnoty z defaults a porovna je s aktualne definovanymi, pokud tam je nejaka hodnota navic, tak vyhodi vyjimku.

**Comment by dg** [comment]
+ doplni vychozí hodnoty

**Comment by f3l1x** [comment]
Closed via #610
