### ISSUE TITLE
Database: Connection: undeprecated some methods

### ISSUE THREAD

**Issue by JanTvrdik** [nette/docs#227]

**Comment by f3l1x** [comment]
@dg Jsou podle tebe v database sekci nejaky deprecated veci? Pripadne nevim co znamena "undeprecated" (jakoze byly deprecated a uz nejsou?).

**Comment by dg** [comment]
Nemam paru o co jde

**Comment by f3l1x** [comment]
@JanTvrdik Nepamatujes si, co jsi myslel timto issue? :-) Pripadne, jestli uz to neni aktualni, coz si tak trochu myslim, tak to muzeme zavrit.

**Comment by JanTvrdik** [comment]
Hádám, že je to related k https://github.com/nette/database/commit/be800e5b6d7175ee7488e0c40cf37d91dc82ce22

**Comment by dg** [comment]
A na kterých místech se to týká docky?

**Comment by JanTvrdik** [comment]
Dohledal jsem https://github.com/nette/docs/commit/aef475be9b6458dd7c318bb191bed4a6c32e16b0, ale je to tak staré issue, že to můžeme skoro určitě zavřít. Šlo jenom o to, aby doc bylo zmíněno, že je OK pracovat s Connection instancí.

V současné doc jsem dohledal jenom https://github.com/nette/docs/blob/doc-2.4/en/database-core.texy#L35 a https://github.com/nette/docs/blob/doc-2.4/cs/database-core.texy#L35

**Comment by f3l1x** [comment]
@JanTvrdik Diky moc.
