### ISSUE TITLE
Components: add use-case of a real component, clarify advanced use of components

### ISSUE THREAD

**Issue by klimesf** [nette/docs#238]
ref http://forum.nette.org/cs/17100-co-vylepsit-na-dokumentaci

**Comment by f3l1x** [comment]
What kind of real component do you mean? What about link to @componette. @klimesf

**Comment by f3l1x** [comment]
Chybi napr. priklad vytvoreni tovarny na komponentu (negenerovana).

**Comment by f3l1x** [comment]
Muzeme zavrit? Podle je to dostatecne doreseno zde: https://github.com/nette/docs/pull/638
