### ISSUE TITLE
Debugging: document switching on via $configurator and Tracy, fix info about E_NOTICE/E_WARNING 

### ISSUE THREAD

**Issue by klimesf** [nette/docs#240]
ref http://forum.nette.org/cs/17100-co-vylepsit-na-dokumentaci

**Comment by f3l1x** [comment]
@dg I think there's correct `E_NOTICE`, WDYT?

https://github.com/nette/docs/blob/nette.org/tracy/en/homepage.texy#L92

**Comment by dg** [comment]
Seems correct.
