### ISSUE TITLE
Projít pořádně quick start, že funguje na Nette 2.3

### ISSUE THREAD

**Issue by pilec** [nette/docs#247]

**Comment by chemix** [comment]
https://github.com/nette/web-content/pull/251

**Comment by chemix** [comment]
chybi teda jeste EN mutace

**Comment by f3l1x** [comment]
- anglicka mutace (:hammer:) https://doc.nette.org/en/2.3/quickstart 
- projit funkcnost (:hammer:)

V aktualni moment zaviram, pokud se objevi nejaka nove chyba, klidne otevrete konkretni issue. 
Diky moc. :+1:
