### ISSUE TITLE
Security: jak vytvorit permission

### ISSUE THREAD

**Issue by matej21** [nette/docs#260]
zminit dve moznosti, 
- ciste v neonu se setup
- factory

**Comment by f3l1x** [comment]
I think is already mentioned.

- https://doc.nette.org/cs/2.4/configuring#toc-security
- https://doc.nette.org/cs/2.4/access-control#toc-pouziti-v-aplikaci

I'll update a few tiny things.

**Comment by f3l1x** [comment]
Related with: https://github.com/nette/docs/pull/563
