### ISSUE TITLE
Fórum: čas < 1 minuta nepřeložen

### ISSUE THREAD

**Issue by pilec** [nette/docs#272]
Přiznám se, že nevím jestli to dávám do dobrýho repa, kdyžtak close.
![snimek obrazovky 2015-03-19 v 16 03 33](https://cloud.githubusercontent.com/assets/557455/6733336/e3f94c2a-ce51-11e4-82a3-30f3998999fb.png)

**Comment by dg** [comment]
`less than a minute from now` znamená za minutu, takže asi rozdíl mezi časem na počítači a na serveru.

**Comment by pilec** [comment]
Hmm, je to na Macu, takže mám čas syncnutý, co na serveru? a český překlad mi dává `méně než minuta od teď`.

**Comment by f3l1x** [comment]
S dovolenim to zaviram, protoze to moc nesouvisi s dokumentaci. Pripadne bych to doresil na foru, pokud je to stale aktualni. @dg toho tedka upravuje stejne vice.

**Comment by dg** [comment]
Tohle je detail, na který kašlu.
