### ISSUE TITLE
Utils: Lépe zdokumentovat Nette\Utils

### ISSUE THREAD

**Issue by klimesf** [nette/docs#275]
ref https://www.youtube.com/watch?v=sP9qs0m74yA
- [x] Přeorganizovat Nette\Utils
- [x] Zdokumentovat další funkce (viz přednáška)

**Comment by klimesf** [comment]
http://doc.nette.org/en/2.3/strings
Mi přijde zbytečně ploché a navigace příliš dlouhá (na 13" se mi skoro nevejde na monitor). Možná rozdělit do sekcí?

**Comment by JanTvrdik** [comment]
Je to sice ploché, ale imho se v tom orientuje dobře.

**Comment by klimesf** [comment]
Zkusím poslat vylepšení :) porovnáme, uvidíme. Minimálně s Regular Expressions je potřeba něco udělat.

**Comment by f3l1x** [comment]
Missing methods:

- [ ] substring
- [ ] normalizeNewLines
- [ ] toAscii
- [ ] firstLower
- [ ] findPrefix
- [ ] reverse
- [ ] before
- [ ] after
- [ ] indexOf

**Comment by f3l1x** [comment]
Complete. 👍 

Good job guys.
