### ISSUE TITLE
[EN] Terms of use - broken link in footer

### ISSUE THREAD

**Issue by Cactucs** [nette/docs#288]
In the footer of Nette's page is a link to "Terms of use", but it causes 404 error. 

I haven't found it in this repo, but it is the best repo where to open this issue.

I think only @dg can fix it.

**Comment by Majkl578** [comment]
it's in www branch, here: https://github.com/nette/web-content/blob/nette.org/www/cs/terms-of-use.texy. It needs to be translated first (and probably verified by a translator afterwards since it's a legal document).

**Comment by f3l1x** [comment]
I will translate it. :-)

**Comment by f3l1x** [comment]
Closed via #544
