### ISSUE TITLE
better info about fork & pull request 

### ISSUE THREAD

**Issue by chemix** [nette/docs#291]
I found this nice footer on composer page... 

![image](https://cloud.githubusercontent.com/assets/42802/7464740/d525fa66-f2c5-11e4-9ad6-2d11fad7d40b.png)

**Comment by Cactucs** [comment]
:+1:

**Comment by klimesf** [comment]
:+1:

**Comment by f3l1x** [comment]
@chemix Could you please make some sketch? :-)

**Comment by dg** [comment]
IMHO current `Vylepšit tuto stránku` is enough.

**Comment by chemix** [comment]
![image](https://user-images.githubusercontent.com/42802/27555899-ce2a8ecc-5ab3-11e7-8c17-0dd0fa761bb0.png)

**Comment by f3l1x** [comment]
![documentation___nette_framework](https://user-images.githubusercontent.com/538058/27573193-e9f456da-5b10-11e7-8a0a-53da567382c8.png)

Maybe some spacing @dg
