### ISSUE TITLE
Databaze: spatne info o vytvareni contextu

### ISSUE THREAD

**Issue by matej21** [nette/docs#301]
http://doc.nette.org/cs/2.3/database#toc-dotazy

vyzaduje IStructure (+ nekolik nepovinnych parametru)

nebo zminovat to vubec, jak ten context vytvorit? bez tech nepovinnych parametru stejne spousta veci fungovat nebude (discovered conventions, accessed cache...) a kdybychom tam uvedli kompletni postup, tak to bude vypadat az moc slozite :)

**Comment by matej21** [comment]
a asi uplne presunout info o Contextu az do Database\Table kapitoly, pouziti connection pro queries jiz neni deprecated, takze je zbytecne ho v teto kapitole vytvaret.

**Comment by matej21** [comment]
ref #354

**Comment by f3l1x** [comment]
Rekl bych, ze jsem to odbavil. Muzes na to @matej21 mrknout? Pripadne @dg co myslis?

**Comment by matej21** [comment]
:+1:
