### ISSUE TITLE
Add documentation of Nette\Application\UI\Multiplier

### ISSUE THREAD

**Issue by klimesf** [nette/docs#322]
ref http://pla.nette.org/cs/multiplier

**Comment by dg** [comment]
@klimesf  can you send pull request?

**Comment by klimesf** [comment]
@dg I'm sorry, I have been swamped lately (see my [current streak](https://github.com/klimesf)), and I will be at least for the next month. I can send the PR then, if someone else doesn't fix this in the meantime.

**Comment by f3l1x** [comment]
Already resolves by https://github.com/nette/docs/pull/558
