### ISSUE TITLE
Latte Default Macros/Filters

### ISSUE THREAD

**Issue by mishak87** [nette/docs#334]
Differentiate what is available when using only Latte and in Nette application.

**Comment by f3l1x** [comment]
Pridavam kontext.
-----

Nejspis je mysleno toto:

https://api.nette.org/2.4/source-Bridges.ApplicationLatte.TemplateFactory.php.html#82-95

```
 82:         $latte->addFilter('url', 'rawurlencode'); // back compatiblity
 83:         foreach (['normalize', 'toAscii', 'webalize', 'reverse'] as $name) {
 84:             $latte->addFilter($name, 'Nette\Utils\Strings::' . $name);
 85:         }
 86:         $latte->addFilter('null', function () {});
 87:         $latte->addFilter('modifyDate', function ($time, $delta, $unit = null) {
 88:             return $time == null ? null : Nette\Utils\DateTime::from($time)->modify($delta . $unit); // intentionally ==
 89:         });
 90: 
 91:         if (!isset($latte->getFilters()['translate'])) {
 92:             $latte->addFilter('translate', function (Latte\Runtime\FilterInfo $fi) {
 93:                 throw new Nette\InvalidStateException('Translator has not been set. Set translator using $template->setTranslator().');
 94:             });
 95:         }
```

**Comment by f3l1x** [comment]
Otazkou je, zda-li je to vubec potreba. A jeslti ano, nejspis by musela vzniknout nova stranka spadajici pod `Application`.

**Comment by dg** [comment]
To už jsme vyřešili, ne?  https://github.com/nette/docs/issues/511#issuecomment-316460590

**Comment by f3l1x** [comment]
To jo, to jo. Ale mozna to vic souvisi s TemplateFactory, coz by se hodilo mit nekde popsany.

**Comment by f3l1x** [comment]
Jestli ti to @dg prijde oukey, klidne muzeme zavrit (a pridat `completed` label). Pripadne, jestli ne, kam s tim? :-)
