### ISSUE TITLE
Konfigurace komponent - kam umistovat?

### ISSUE THREAD

**Issue by matej21** [nette/docs#355]
Spousta komponent ma zduplikovany informace o konfiguraci, napriklad nette/database:
- http://doc.nette.org/cs/2.3/configuring#toc-databaze
- http://doc.nette.org/cs/2.3/database#toc-vytvoreni-pripojeni

tedy v kapitole o database a pak v kapitole o konfiguraci. Jak toto resit?
1. vsechny informace o konfiguraci by mely byt jak u komponenty, tak na strance konfigurace
2. u komponenty by mely byt zakladni informace o konfiguraci a odkaz na tu stranku s konfiguraci
3. obracene - na strance s konfiguraci zakladni info a vsechny informace u komponenty

ja jsem pro 2.

**Comment by mrtnzlml** [comment]
Já jsem pro 3. Když hledáš informace o konfiguraci databáze, tak (alespoň já) hledám databázi, nikoliv konfiguraci obecně.

**Comment by matej21** [comment]
kdyby 3... melo by vubec smysl tam nechavat tu zakladni konfiguraci? Co takhle tam udelat jen rozcestnik (treba tabulku) s nazvem komponenty a odkazem na konfig?

**Comment by matej21** [comment]
ta 1 by byla dobra pro uzivatele, ale driv nebo dyl by se zacly ty informace rozchazet. Jedine ze by tam nekdo naprogramoval reference na kapitoly z jinych clanku, ze by se samy vlozily.. hmm? :D

**Comment by mrtnzlml** [comment]
Právě kvůli rozcházení informací se mi víc líbí 3. Určitě by bylo fajn, kdyby tam byl dobře viditelný proklik na tu konkrétní konfiguraci, protože to k tomu svým způsobem patří, ale víc bych to nehrotil. Ale lépe ať se k tomu vyjádří ještě někdo jiný...

**Comment by Unlink** [comment]
Mne by si celkom páčili tie referencie, že by si to písal priamo ku komponente, a tá stránka s konfiguráciou by to len zobrazovala, ak nie, tak potom len odkaz na príslušnú kapitolu danej komponenty.
Pretože tiež som názoru ako martin, že ak hľadám niečo o konfigurácii databázy, tak by som to skôr hľadal tam.

**Comment by f3l1x** [comment]
Co udelam s timhle? :-) 

Rekl bych, ze vic intuitivni je mit konfiguraci u jednotlivych komponent. Clovek treba ani nevi, jaky vsechny komponenty nette ma a spis narazi na nette/database nez na stranku konfigurace, kde bude spousta informaci.

Co na to @dg @chemix ?

**Comment by chemix** [comment]
Tady je jen potreba dat vedet ze to je konfigurace s DI v Nette aplikaci a pak mi dava smysl to mit u te komponenty

**Comment by f3l1x** [comment]
To bude vyzadovat docela dost uprav. =/

**Comment by f3l1x** [comment]
Domluvili jsme se s @dg, ze vsechnu konfiguraci budeme vest zde: https://doc.nette.org/cs/2.4/configuring. 

A z jednotlivych komponent budeme odkazovat.

**Comment by f3l1x** [comment]
Pokud nekdo dostane lepsi napad, poslete PR at se muzeme bavit nad realnym kodem. 

Diky @mrtnzlml @Unlink @matej21 @chemix za nazory a zalozeni ticketu.
