### ISSUE TITLE
Validace formulářových polí

### ISSUE THREAD

**Issue by pavelvondrasek** [nette/docs#378]
Možná pro začátečníky dobré zmínit, že kromě defaultních validačních funkcí fomulářového pole lze použít i callback nebo vytvořit vlastní validační funkci. V druhém případě by se hodila u nějaká ukázka, jak to udělat.

**Comment by f3l1x** [comment]
Dobry napad.

**Comment by chemix** [comment]
Tenhle radek tam je leta co pamatuji: 

Můžeme si také přidat vlastní validátory. Metody addRule() a addCondition() totiž jako název pravidla akceptují callback:

https://doc.nette.org/cs/2.4/forms#toc-validace

**Comment by f3l1x** [comment]
@chemix Mas recht, tim padem je to jasne.
