### ISSUE TITLE
V kapitole Lokalizace odkázat do addons

### ISSUE THREAD

**Issue by pavelvondrasek** [nette/docs#379]
Protože většina začátečníků, kteří na fóru mají problém pochopit i namespace, si asi nenapíše svůj vlastní translation, tak by asi bylo dobré zmínit alespoň odkaz na addons, že tam jsou příklady translationů. Případně možná by bylo lepší zmínit přímo Kdyby/Translation, ale to asi neprojde :D

**Comment by dg** [comment]
@pavelvondrasek  can you send pull request?

**Comment by f3l1x** [comment]
I've prepared a PR.
