### ISSUE TITLE
Configuring: better description for DI

### ISSUE THREAD

**Issue by racinmat** [nette/docs#386]
better description for 
DI#

di:
    debugger: true  # aktivuje panel v Debugger baru 
(in title would be bette Dependency Injection and that which panel will be activated)

**Comment by dg** [comment]
@racinmat  can you send pull request?

**Comment by f3l1x** [comment]
Adding more context for the future.

https://doc.nette.org/en/2.4/configuring#toc-di-container

![selection_015](https://user-images.githubusercontent.com/538058/27576862-c8586260-5b1e-11e7-8e26-9b65a98f6346.png)

**Comment by f3l1x** [comment]
@dg Maybe we can add some screenshot to that section? WDYT?

**Comment by dg** [comment]
DI panel is active by default in Nette 2.4

**Comment by f3l1x** [comment]
Well, `DI container` is better then `DI` and which panel will be activated is mentioned also. 

I'm closing this. Feel free to create another issue. Thanks @racinmat
