### ISSUE TITLE
Vytvořit vlastní kapitolu služeb

### ISSUE THREAD

**Issue by pavelvondrasek** [nette/docs#387]
Přesunout do ní obsah získávání závislostí a konfigurace. 
Zmínit výhody a nevýhody služeb.
Také chybí vysvětlení, jak lze pomocí @ odkazovat na jiné služby.

**Comment by f3l1x** [comment]
Neni to jedna z techto?

- https://doc.nette.org/cs/2.4/configuring
- https://doc.nette.org/cs/2.4/dependency-injection
- https://doc.nette.org/cs/2.4/di-usage
- https://doc.nette.org/cs/2.4/di-extensions

Me prijdou docela dostacujici. Co ti tam chybi @pavelvondrasek ?

**Comment by f3l1x** [comment]
ping @pavelvondrasek

**Comment by f3l1x** [comment]
@dg Myslim, ze tohle jsme vyresili, co myslis?
