### ISSUE TITLE
defaultní out filter

### ISSUE THREAD

**Issue by Keeehi** [nette/docs#392]
Dle commitu [448749a](https://github.com/nette/application/commit/448749a558eb4cf50c4bc6e3e31aa104597349df) bych řekl, že defaultním out filtrem není rawurldecode ale [param2path](https://github.com/nette/application/blob/master/src/Application/Routers/Route.php#L768-L771)

[Řádek kde je to asi špatně](https://github.com/nette/web-content/blob/doc-2.3/cs/routing.texy#L380)

**Comment by dg** [comment]
@Keeehi  can you send pull request?
