### ISSUE TITLE
Opening editor url handler under gnome (ubuntu)

### ISSUE THREAD

**Issue by alesculek** [nette/docs#394]
Hi,

I have update to opening editor:// url handler under gnome (on ubuntu). **The way with gconftool-2 didn't work for me**.

I've found solution. I want to send PR, but I don't know if solution on website is working for someone?
https://pla.nette.org/cs/jak-otevrit-soubor-z-debuggeru-v-editoru

**Solution for me**

1) Create desktop entry

```
touch /usr/local/share/applications/editor.desktop
# open in nano (or another editor you like)
nano /usr/local/share/applications/editor.desktop
```

insert following (set path to your editor.sh script):

```
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Terminal=false
Exec=/usr/local/bin/editor %u
Name=Editor
Comment=Editor-Url handler
Icon=
Categories=Application;
MimeType=x-scheme-handler/editor;
```

2) Update gnome desktop database

```
sudo update-desktop-database
```

**Prepared command in run-editor.sh not worked for me as well with netbeans**

I've used instllation from netbeans' pages, installed for **all users**
But run command (from netbeans.desktop) is:

```
/bin/sh "/usr/local/netbeans-<VERSION>/bin/netbeans"
```

not just a

```
netbeans
```

so **suggest to: replace it or link to local bin**

```
sudo ln -s /usr/local/netbeans-<VERSION>/bin/netbeans /usr/local/bin/netbeans
```

**I want just save time to other users with solving opening handlers**

**Comment by vlastavesely** [comment]
Have you tried a tool that is already part of Tracy?
https://github.com/nette/tracy/tree/master/tools/open-in-editor

**Comment by f3l1x** [comment]
I'm closing it now, feel free to reopen in case of problems. 

As @vlastavesely said, take a look at Tracy's page (https://github.com/nette/tracy/tree/master/tools/open-in-editor).

Thank you.
