### ISSUE TITLE
Článek: Rozšíření pro DI kontainer => odkaz => stránka nenalezena

### ISSUE THREAD

**Issue by Machy8** [nette/docs#401]
Odkaz **"některá uživatelská nastavení"** na konci článku v části _afterCompile()_ odkazuje na neexistující stránku.

[Odkaz na článek](https://doc.nette.org/cs/2.3/di-extensions)

**Comment by Myiyk** [comment]
Link na nejpodobnější aktuální kód je https://api.nette.org/2.4.0/source-DI.Extensions.DIExtension.php.html#49-75

**Comment by dg** [comment]
@Machy8  can you send pull request?

**Comment by Machy8** [comment]
[Here](https://github.com/nette/web-content/pull/448). I wasn't sure how to wrote the link correctly, so I used the link @Myiyk added in his comments.

**Comment by f3l1x** [comment]
I'm not sure, but it's solved @Machy8?

**Comment by Machy8** [comment]
@f3l1x It was merged in merged https://github.com/nette/docs/pull/448 :)

**Comment by f3l1x** [comment]
Cool. Thanks.
