### ISSUE TITLE
Quickstart: Nepřesnost - přihlašovací formulář

### ISSUE THREAD

**Issue by landsman** [nette/docs#409]
V kapitole: https://doc.nette.org/cs/2.3/quickstart/authentication#toc-prihlasovaci-formular se mluví o metodě createComponentSignInForm v presenteru SignPresenter, která by měla obsahovat formulář, ten je však volán až z továrničky SignFormFactory (/app/forms/SignFormFactory.php) metodou create.

**Comment by dg** [comment]
@Studioartcz can you send pull request?

**Comment by f3l1x** [comment]
ping @Studioartcz

**Comment by f3l1x** [comment]
@landsman Ahoj, mrknes prosim na to a posles PR? :-)

**Comment by dg** [comment]
Protože Quickstart už nevychází ze Sandboxu, chce to jen změnit

```
To je ale náhodička, v Sandboxu již jeden takový presenter je připraven! Můžeme ho jednoduše použít. Pojďme si tedy projít, co obsahuje a jak funguje.

Začneme s přihlašovacím formulářem. Již víme jak formuláře v presenterech fungují. Otevřeme si tedy presenter SignPresenter a najdeme metodu createComponentSignInForm. Měl by vypadat nějak takto:
```

na 

```
Začneme s přihlašovacím formulářem. Již víme jak formuláře v presenterech fungují. Vytvoříme si tedy presenter SignPresenter a zapíšeme do něj metodu createComponentSignInForm. Měla by vypadat nějak takto:
```
