### ISSUE TITLE
quickstart - no presenter mapping in config

### ISSUE THREAD

**Issue by vvoody-** [nette/docs#46]
V zdrojákoch quickstartu bol oproti sanboxu odstránený mapping https://github.com/nette/tutorial-quickstart/blob/master/app/config/config.neon. Myslím že by o tom mala byť zmienka v samotnom quickstarte. Začiatočník sa môže zadrhnúť pri vytváraní PostPresenter podla http://doc.nette.org/cs/2.1/quickstart/single-post ktorému nepridá namespace, nepomôže ani kontrola presenteru oproti git zdrojákom https://github.com/nette/tutorial-quickstart/blob/master/app/presenters/PostPresenter.php tam namespace tiež nieje.

http://forum.nette.org/cs/16592-zadrhel-pri-quick-startu-nelze-nalezt-tridu-basepresenter

**Comment by f3l1x** [comment]
Fixed in many branches. Thanks for reporting. ;-)

Feel free to open new issues.

:+1:
