### ISSUE TITLE
php-language-enhancements: volitelný getter?

### ISSUE THREAD

**Issue by lentilcz** [nette/docs#491]
V dokumentaci se píše:
`Getter i setter je volitelný, mohou tedy existovat read-only nebo write-only property`

nemá být getter poviný (read-only) a setter volitelný (read-write)? Nevim jak je to v kódu Nette, ale pokud je getter volitelný, tka nechtělo by to opravit?

**Comment by Myiyk** [comment]
Může být pouze setter bez getteru. Aby šlo jenom nastavit hodnotu, ale nejde ji číst.

Např. heslo, to lze jenom nastavit a potom porovnávat, ale nelze jej číst (v plain-text podobě).
