### ISSUE TITLE
Let´s add automatic spell checking tool and hook it in travis ci

### ISSUE THREAD

**Issue by lukasneubauer** [nette/docs#501]
I guess that we could include some kind of automatic grammar checker, for both the czech and english `.texy` files, probably as a command line tool or script, and add it in `.travis.yml` to ensure, that at least the most common spelling mistakes will not get in the public release of the docs.

The problem though is that I myself have no idea or knowledge, at least at this point in time, of any such tool. I don´t know, if the os used by travis has such a tool, or if it has to be implemented as a bash script.

What is your take on this? Any ideas or suggestions?

**Comment by f3l1x** [comment]
Related: #608, #624

We have an extra branch **spellchecker**, please take a look how to install and run. I don't think it could be part of the CI process, because the dictionary must be a very comprehensive. Time and again we could run it. 

https://github.com/nette/docs/tree/spellchecker
