### ISSUE TITLE
Latte: missing webalize filter

### ISSUE THREAD

**Issue by martinsifra** [nette/docs#511]
Is there any reason why description of `webalize` filter was dropped? In previous version was mentioned and there was no mention about it in releases.

**Comment by dg** [comment]
It is not in pure Latte, it is only in presenters.

**Comment by martinsifra** [comment]
Ha, I thought so. I've tried to find some mention in current version but without success. Maybe we should to mention this feature somewhere. Any ideas?

**Comment by f3l1x** [comment]
I've found it only on `Strings` page (https://doc.nette.org/cs/2.4/strings#toc-webalize).

Where would you mention it @martinsifra?

**Comment by f3l1x** [comment]
Well, I think that we could mention that [these filters are added in TemplateFactory](https://api.nette.org/2.4/source-Bridges.ApplicationLatte.TemplateFactory.php.html#82-95).

- normalize
- toAscii
- webalize
- reverse

**Comment by dg** [comment]
- normalize myslím nikdo v Latte nepoužívá, nechal bych to žít jen kvůli zpětné kompatibilitě.
- reverse můžu přidat do Latte a tak ho legálně zdokumentovat
- toAscii imho taky nikdo v Latte nevyužije
- webalize by se dalo vyřešit tak, že v bych to přidal do Latte s tím, že by to vyžadovalo nainstalovat nette/utils. A s touto poznámkou by se to přidalo do docky

**Comment by f3l1x** [comment]
Souhlasim. Dali bychom to do docky k latte vid?

**Comment by dg** [comment]
Jasně

**Comment by f3l1x** [comment]
Ok, kdyz to pushnes do latte, doplnim to do docky.

**Comment by dg** [comment]
Je to v Latte

**Comment by f3l1x** [comment]
Assigned to: @premekkoch 

-----

Premku, je potreba pridat do dokumentace k latte, ze je tam filtr reverse a take webalize. K webalize drobnou poznamku, ze je potreba mit nette/utils k tomu (mozna odkaz na nette/utils, pokud se to bude hodit).

Kdyby cokoli, napis.

**Comment by f3l1x** [comment]
Closed via #600. 

Diky moc @premekkoch (https://github.com/nette/docs/commit/c56f0dc9933ee3d32ca4211ba30f881461ab58e2).
