### ISSUE TITLE
[2.3] Nette\Database - missing 2nd parameter in Context

### ISSUE THREAD

**Issue by f3l1x** [nette/docs#535]
Origin: https://forum.nette.org/en/25741-outdated-nette-database-documentation-missing-2nd-param-for-context

**Comment by matej21** [comment]
v ceske verzi je to opravene https://github.com/nette/docs/commit/2d45f26098007667fa989beb3e1b36e2f010b809 bohuzel jsem pres veskere sliby nedodal EN verzi. zkusim to aspon najit a pushnout, at na tom nekdo muze stavet

btw, imho je zbytecna prace fixovat neco proti 2.3 verzi

**Comment by f3l1x** [comment]
No, asi bych do 2.3 nedaval nove veci, ale kdyz uz to nekdo zmini, tak bych to fixnul. Klidne to backportuju ;-) Ale jestli najdes cas, tak to bude super.

**Comment by f3l1x** [comment]
@matej21 Ujmes se toho? Muzu te priradit?

**Comment by f3l1x** [comment]
Related: https://github.com/nette/docs/issues/535

**Comment by f3l1x** [comment]
Pokusil jsem se sesynchronizovat EN/CZ verzi u database-table.

#547

**Comment by f3l1x** [comment]
S @dg jsme se shodli, ze to nejspis nema cenu upravovat ve 2.3 apod. Jestli jste pro.

**Comment by f3l1x** [comment]
Ping @matej21.. :question:

**Comment by f3l1x** [comment]
Resolved.
