### ISSUE TITLE
HTTP: document CSP support & nonce

### ISSUE THREAD

**Issue by dg** [nette/docs#550]
In documentation is missing https://forum.nette.org/en/27918-nette-framework-2-4-2017-01-19

**Comment by mabar** [comment]
Please note in docs that booleans attributes like `block-all-mixed-content` must be written without value or with null to be generated properly. I've expected that I should write `block-all-mixed-content: true` when I was implementing CSP.

**Comment by f3l1x** [comment]
Idealne pridat do:

- [ ] latte stranky
- [ ] tracy funguje automaticky
- [ ] do configuration

**Comment by f3l1x** [comment]
Assigned: @matej21
