### ISSUE TITLE
Json - add information about sendResponse(new JsonResponse)

### ISSUE THREAD

**Issue by nufue** [nette/docs#555]
Current JSON documentation page only contains info about Nette\Utils\Json class, but I think it would be useful if it mentioned how to send a Json response from the presenter. The idea came from [this forum thread](https://forum.nette.org/en/29005-how-to-make-a-json-webservice-from-presenter).

**Comment by f3l1x** [comment]
Thanks @nufue.

-----

What do you think @dg?

**Comment by dg** [comment]
Let's go

**Comment by f3l1x** [comment]
@nufue Could you prepare a PR? :-)

**Comment by nufue** [comment]
@f3l1x PR #556 created

**Comment by f3l1x** [comment]
Thank you @nufue for PR and @dg for correction.
