### ISSUE TITLE
Utils - document FileSystem

### ISSUE THREAD

**Issue by f3l1x** [nette/docs#585]
- https://api.nette.org/2.4/Nette.Utils.FileSystem.html

**Comment by f3l1x** [comment]
Closed via: https://github.com/nette/docs/commit/b6f9f6a20b2f078d687e4a7bfe8ad8936c62a9e6

Thanks @landsman

**Comment by dg** [comment]
This commit is related to Arrays

**Comment by f3l1x** [comment]
Jej, spatny ticket, omlouvam se.

**Comment by f3l1x** [comment]
Assigned to: @bretislavstepan

**Comment by f3l1x** [comment]
Pridam jeste odkaz na homepage, pak to zavru @bretislavstepan a @dg.

**Comment by f3l1x** [comment]
Chybi odkaz z homepage. Tedka se tam neda proklikat, protoze ani Utils nemaji odkaz z homepage.

**Comment by dg** [comment]
Už jsem ho tam dal
