### ISSUE TITLE
Readme - leave a note about code-checker

### ISSUE THREAD

**Issue by f3l1x** [nette/docs#587]
- how to install it
- how to use it before PR

**Comment by nufue** [comment]
_How to install it_ is covered in [https://github.com/nette/code-checker/blob/master/readme.md](https://github.com/nette/code-checker/blob/master/readme.md).

_How to use it_ - where would you put it? Maybe to [Writing the Documentation](https://nette.org/en/writing#toc-contributing)?

**Comment by f3l1x** [comment]
I mean README in this repo ;-) And yes, in Writing the Documentation, exactly.
