### ISSUE TITLE
SafeStream - enhancement

### ISSUE THREAD

**Issue by f3l1x** [nette/docs#595]
- [x] install note
- [ ] how to register

**Comment by dg** [comment]
It is registered automatically

**Comment by f3l1x** [comment]
Ano, to je fakt, zjistil jsem to, kdyz jsem se dival do composeru. :-)
Nemyslis, ze by bylo dobre to zminit v textu?

**Comment by f3l1x** [comment]
Text: `Protokol se zpřístupní automaticky při načtení Nette Framework. A pak stačí jen uvést nette.safe:// před jménem souboru:`, neni uplne presny. 

Pokud chces balicek pouzivat i samostatne.

**Comment by dg** [comment]
Jo, to by se mohlo.

**Comment by f3l1x** [comment]
Install note uz je: ![selection_041](https://user-images.githubusercontent.com/538058/28492028-5cad4f6c-6efb-11e7-9c68-4451b840a069.png)

**Comment by dg** [comment]
Jasně, on je to 5 let starý text.
