### ISSUE TITLE
ArrayHash - create docs

### ISSUE THREAD

**Issue by f3l1x** [nette/docs#603]
- API: https://api.nette.org/2.4/Nette.Utils.ArrayHash.html
- Page: https://doc.nette.org/cs/2.4/arrays

-----

- pridat do stranky `arrays`
- pridat nadpis h2 (ArrayHash)
- pridat nadpis h2 (Arrays)

**Comment by premekkoch** [comment]
beru

**Comment by f3l1x** [comment]
Solved via #609 & 687a20a00da972f665d79d881d51388319636460. Thanks @premekkoch
