### ISSUE TITLE
ArrayList - create docs

### ISSUE THREAD

**Issue by f3l1x** [nette/docs#604]
- API: https://api.nette.org/2.4/Nette.Utils.ArrayList.html
- Page: https://doc.nette.org/cs/2.4/arrays

-----

- pridat nadpis h2 (ArrayList)
- pridat nadpis h2 (Arrays) 
- zdokumentovat metody z ArrayListu

**Comment by premekkoch** [comment]
beru

**Comment by f3l1x** [comment]
Solved via #609 & 687a20a00da972f665d79d881d51388319636460. Thanks @premekkoch
