### ISSUE TITLE
Forms - manual rendering

### ISSUE THREAD

**Issue by mabar** [nette/docs#625]
{label labeNamel /} {input inputName} etc.

**Comment by f3l1x** [comment]
I've found manual rendering here: https://doc.nette.org/cs/2.4/form-rendering#toc-manualni-vykreslovani

**Comment by mabar** [comment]
Oh, sorry. I foolishly accessed documentation throught google and not checked if there are any other pages :/

**Comment by f3l1x** [comment]
No problem, feel free to join us on gitter or slack. 

https://gitter.im/nette/nette/
https://gitter.im/nette/nette/cs
