### ISSUE TITLE
QuickStart - keep only for latest stable Nette 

### ISSUE THREAD

**Issue by f3l1x** [nette/docs#628]
- [ ] drop all tutorials older then v2.4 (after discussing with @dg)
- [ ] merge v2.4 into master in nette/tutorial-quickstart
- [ ] remove branches in nette/tutorial-quickstart

**Comment by petrparolek** [comment]
why?

**Comment by dg** [comment]
Imho current state is ok, or not?

**Comment by mabar** [comment]
Please no. Its good idea to force people to learn newest version. But when they can so they will do it without this change. Quick start for older Nette versions is still good when sb. start working in company where is used older version of Nette and know nothing about it.

**Comment by f3l1x** [comment]
It's oukey ;-) We're done here. QS for version 2.3 is dropped the rest stays.

**Comment by f3l1x** [comment]
I must say that QS will not be updated for other then latest version.
