### ISSUE TITLE
Remove redirect inside try

### ISSUE THREAD

**Issue by JanGalek** [nette/docs#631]
V Dokumentaci, konkrétně zde https://doc.nette.org/cs/2.4/access-control#toc-autentizace (ještě prohledám zbytek) se nachází v try přesměrování, což vede k tomu, že dostaneme vyjímku `Nette\Application\AbortException`

přesměrování by se mělo dít až po try ;)

konkrétní případ:

```php
public function actionDefault()
{
	try {
		$this->redirect('Redirect:default');
	} catch (\Exception $e) {
		bdump($e);
		Debugger::log($e->getMessage());
	}
}
```

Edit: pošlu PR, hned jak se dořeší https://github.com/nette/docs/pull/626 ;)

**Comment by dg** [comment]
Zachytávání `\Exception` nikde v dokumentaci nevidím.

**Comment by JanGalek** [comment]
máš pravdu, moje chyba
