### ISSUE TITLE
Planette forms replicator link broken

### ISSUE THREAD

**Issue by maral** [nette/docs#647]
Broken link at https://pla.nette.org/

docs/pla/cs/homepage.texy:11
| [Dynamický počet položek ve formuláři |addons:cs/form-container-replicator] | Addon

The supposed link is this:
https://componette.com/kdyby/formsreplicator/

I would fix it, however I don't know how does the magic addons links work, so I leave it to professionals :)

**Comment by dg** [comment]
Fixed

**Comment by f3l1x** [comment]
Thank you for reporting @maral
