### ISSUE TITLE
Composer - page enhancements

### ISSUE THREAD

**Issue by f3l1x** [nette/docs#649]
- [ ] mention [hirak/prestissimo](https://github.com/hirak/prestissimo)
- [ ] composer init to create library
- [ ] composer scripts

**Comment by dg** [comment]
Myslíš, že je potřeba investovat energii do dokumentování cizí knihovny?

**Comment by f3l1x** [comment]
Mam to za par minut sepsane a treba to nekomu pomuze pri tvorbe jeho knihoven. Urcite to hirak/prestissimo je super nastroj, ktery porad nekdo nezna. :-)

**Comment by JanGalek** [comment]
Souhlasím, že je to super knihovna, ale nejsem si jistý, jestli by měla být přímo v nette dokumentaci. Možná v nějaké podsekci (subdomain), kde by se tedy mohli sepisovat cizí užitečné knihovny :)

**Comment by dg** [comment]
Ono to mělo svůj historický důvod, kdy Composer znalo jen málo programátorů, ale dnes bych spíš tuhle stránku zrušil a tipy na související nástroje dal na blog.

**Comment by JanGalek** [comment]
Tak to nahodit na blog a pak odkaz do tipů :)

**Comment by f3l1x** [comment]
@dg Tak to pak hodime na planette?

**Comment by dg** [comment]
Myslis stanku Composer nebo ty věci, které jsi chtěl do ní doplnit?

Já už bych do ní fakt nic nedoplňoval. Pokročilé použití Composeru nepatří IMHO do dokumentace Nette, ale vůbec by to nevadilo na blogu Nette. Případně na planette.

**Comment by f3l1x** [comment]
Rozumim. Uziviram a hodime to do planette.
