### ISSUE TITLE
Dependency injection article - Incorrect references to createArticle

### ISSUE THREAD

**Issue by krisarsov** [nette/docs#653]
Hello,

I think the references to `createServiceArticle` on the following lines need to be changed to `createArticle`:
https://github.com/nette/docs/blob/doc-2.4/en/dependency-injection.texy#L272
https://github.com/nette/docs/blob/doc-2.4/en/dependency-injection.texy#L280
https://github.com/nette/docs/blob/doc-2.4/en/dependency-injection.texy#L283
https://github.com/nette/docs/blob/doc-2.4/en/dependency-injection.texy#L328

**Comment by f3l1x** [comment]
Hi. 

Why do you think? Do you test it on your generated DI Container? I think it's oukey.

**Comment by dg** [comment]
@krisarsov You're right. However, the whole part about `createArticle` is rather confusing, I'd rather remove it.
