### ISSUE TITLE
Zdokumentovat Control getParameterId

### ISSUE THREAD

**Issue by JanGalek** [nette/docs#657]
Myslím, že by bylo dobré přidat do dokumentace metodu getParameterId.

Nejčastěji jsem totiž potřeboval odesílat ajax na handle v komponentě, a řešil jsem to vždy ošemetně (handle v presenterech a odkaz na plink)

Př.
`pošle při změně inputu`
```js
var count = element.val();
var id = element.attr("data-id");

$.nette.ajax({
	'url':{link changeCountBasket!},
	'data':{
		{$control->getParameterId('id')}: id,
		{$control->getParameterId('count')}: count
	}
});
```

řešilo se i na fóru: https://forum.nette.org/cs/27027-automaticke-generovani-url-parametru-v-komponentach

PR bych se ujal, jen bych potřeboval poradit na jakou stránku v dokumentaci to přidat.

**Comment by dg** [comment]
Asi by se to nejvíc hodilo právě do stránky o AJAXu, tedy https://doc.nette.org/cs/2.4/ajax

**Comment by f3l1x** [comment]
Resolved via #663
