### ISSUE TITLE
Team & Contributors claims Nette was invited (somewhere) by David

### ISSUE THREAD

**Issue by Majkl578** [nette/docs#690]
https://nette.org/contributors

I don't know where Nette was _invited_ to, but it should probably say _invented_.

**Comment by f3l1x** [comment]
Ping @dg

**Comment by f3l1x** [comment]
Looks like it's fixed. Thanks for report @Majkl578.

![image](https://user-images.githubusercontent.com/538058/64539404-baebb580-d31e-11e9-97ab-06a4201d1542.png)
