### ISSUE TITLE
Broken link to Latte iterator api

### ISSUE THREAD

**Issue by Machy8** [nette/docs#700]
Broken link is on the following urls
- Cz: https://latte.nette.org/cs/macros#toc-cykly
- En: https://latte.nette.org/en/macros#toc-loops

In the part
- Cz: "**Její API** disponuje čítačem průchodů a metodami..."
- En: "**Its API** features iteration counter and methods..."

I am sorry, but I don't know by which link I can replace it so I can't send a pull request.

**Comment by f3l1x** [comment]
Hi, is it still relevant? I've tested that links and they work.

**Comment by Machy8** [comment]
@f3l1x It looks like they are already fixed. You can close the issue.

**Comment by f3l1x** [comment]
Cool.

**Comment by Machy8** [comment]
@f3l1x Thanks!
