### ISSUE TITLE
How to link a css file

### ISSUE THREAD

**Issue by rzelnik** [nette/docs#703]
In the [quickstart howto](https://doc.nette.org/en/2.4/quickstart/home-page) there is a CSS file that enhances the look of the blog home page, but there is no instruction, how to link the CSS file to the HTML layout. As a Nette-beginner I don't know how to add an absolute path to the nette app in the link href attribute.

**Comment by rzelnik** [comment]
@dg , thanks a lot for quick response.

**Comment by dg** [comment]
you're welcome
