### ISSUE TITLE
Prev/Next Chapter links in sidebar

### ISSUE THREAD

**Issue by finwe** [nette/docs#728]
I guess it would help a lot if links to previous/next chapter were not only at the bottom of the page, but in the sidebar as well. Preferrably at the top, as it would take only two lines, the other content would not be moved too far and still visible above the fold.

Alternatively, they could be placed between h1 and h2 to the main page content.

Currently, there are no other means of navigating chapters than either scrolling to the bottom or returning to the main page.

**Comment by dg** [comment]
I tried to add it.

**Comment by finwe** [comment]
Cool, seems OK!
