### ISSUE TITLE
English tweaks on Latte homepage

### ISSUE THREAD

**Issue by finwe** [nette/docs#743]
A few remarks about english Latte homepage. Original texts are in _italics_, correction proposals in **_bold italics_**

- correct spelling is _**truly**_ instead of _trully_ in the main claim
- definite article in _Call the Security_ should be omitted, correct is: _**Call Security**_
- mixing tenses in _We have been developing Latte for over 10 years- and counting!_
- unsure what _Over 10 Years_ heading should mean - missing an adjective or a verb.
- maybe an oxford comma in _**highly mature, stable, and widely used**_
- _You don’t have to worry about how to write in Latte._ 
    - Better: _**worry about writing**_
- _You just stick to what you are already know_.
    - _are_ is redundant here
- In _The compiled PHP code is clear and easy_, definite article should be omitted.
- _It is exactly the same like PHP syntax_
    - well, it isn't, exactly.
- _Latte does not lack any important feature._
    - **Lack** usually pairs with uncountables or plurals.
    - Maybe better: _**There are no important features missing in Latte**_

Generally, the translation is clumsy and too close to the Czech original, too "czenglish" in parts. Maybe a more thorough review or a rewrite would be in order, correcting individual sentences is maybe a waste of time.

**Comment by f3l1x** [comment]
Could you please @finwe create a PR for these changes? 🌮

**Comment by finwe** [comment]
I would but there is no place to change this. Home pages are not (or were not at the time of creating this issue) in the repository (or at least no one could point me to them when I asked)

**Comment by dg** [comment]
I will fix it in web code.

**Comment by dg** [comment]
Fixed, thanks
