### ISSUE TITLE
Negative validation rules

### ISSUE THREAD

**Issue by jtojnar** [nette/docs#744]
https://doc.nette.org/en/3.0/form-validation says

> All conditions can be negated with `~` (a tilde), i.e. `addCondition(~Form::NUMBER, ...)` passes validation if field is not filled.

but this has been deprecated in https://github.com/nette/forms/commit/000677fd809362a82c13a21461301d0e8cf950b9. What is the correct method for creating negative validators?

**Comment by milo** [comment]
It is in the commit message `(Negatives for FILLED & EQUAL are BLANK & NOT_EQUAL)`

**Comment by jtojnar** [comment]
Well, I am more concerned about other rules like `~NUMBER`.

**Comment by dg** [comment]
addRule(Form::PATTERN, null, '\D+')`

**Comment by jtojnar** [comment]
Perhaps I should have been clearer, I meant this as a documentation issue. I would open a PR myself but I am not aware of any generic solution, so I opened this issue.

**Comment by dg** [comment]
Sorry, I did not understand.
