### ISSUE TITLE
Broken links to ApiDocs in 3.0

### ISSUE THREAD

**Issue by Rixafy** [nette/docs#762]
When you switch to docs 3.0, every link to api docs return 404. The problem is that new api docs are in folders, not files that are "separated" by `.`, I noticed filter |api in .texty files, so solution would be add condition to filter for docs 3.0 (dots will be replaced with slashes, except the last), so link https://api.nette.org/3.0/Nette.Caching.Storages.MemcachedStorage.html will look like https://api.nette.org/3.0/Nette/Caching/Storages/MemcachedStorage.html.

**Comment by dg** [comment]
Fixed

**Comment by Rixafy** [comment]
There is another broken path in right panel and above next to github link (you need to remove `namespace-` string and replace `.` with `/`). Btw, isn't better open apidocs links in new window? Programmer usually wants to see described some available methods, but also stay on documentation page.

![image](https://user-images.githubusercontent.com/45132928/56974854-f22ba800-6b6f-11e9-8188-db8e51c47815.png)

**Comment by dg** [comment]
Fixed
