### ISSUE TITLE
Translate routing improvements from English to Czech

### ISSUE THREAD

**Issue by JanTvrdik** [nette/docs#81]
I'm looking for someone to translate the latest English version of Routing page to a Czech version. Before you start working on the translation write to this thread. I don't need 3 translations – just one :smile:

**Comment by f3l1x** [comment]
I think this could be closed, because the czech translation is already added and also some english typos.

bad5e2a
37dc6d5
aa2bf14

**Comment by f3l1x** [comment]
Right @Majkl578 ?
