### ISSUE TITLE
Forms: Add HTML attributes to items

### ISSUE THREAD

**Issue by FVesely** [nette/docs#814]
Hello,

based on David answer on forum https://forum.nette.org/cs/33289-jak-nastavim-u-addradiolist-set-attribute#p209822 I want to add this information to documentation. 

I found two sections with HTML attributes https://doc.nette.org/en/3.0/form-rendering#toc-html-attributes and https://doc.nette.org/en/3.0/form-fields#toc-addradiolist and I don't know which one is the right one. :)

**Comment by dg** [comment]
Pozdě, už jsem to tam dopsal :-)

**Comment by FVesely** [comment]
@dg was faster :) https://github.com/nette/docs/commit/582f7789583614c69ad8414e6a285c59dcf63d56
