### ISSUE TITLE
Convertor: invalid submenu HTML

### ISSUE THREAD

**Issue by thejoeejoee** [nette/docs#816]
On all docs pages are in generated HTML [invalid markup](https://validator.w3.org/nu/?doc=https%3A%2F%2Fdoc.nette.org%2Fen%2F3.0%2Fquickstart%2Fgetting-started), `h2` tags are ended by `h3`:
```html
<h3 >Preface</h2>
...
<h3 class="main" >Create Your First Application</h2>
...
```

**Comment by dg** [comment]
fixed
