### ISSUE TITLE
Latte - API URL generator wrong url

### ISSUE THREAD

**Issue by woytam** [nette/docs#853]
Texy URL generator for API pages, `api` filter, generates wrong URL.
Example, where it generates wrong URL (`[PhpWriter |api:Latte\PhpWriter]`):
https://github.com/nette/docs/blob/2af80899e71850d6fed0386309d8e234767f4665/latte/cs/develop.texy#L207
Expected URL:
```
https://api.nette.org/2.4/Latte.PhpWriter.html
```
Generated:
```
https://api.nette.org/2.4/Latte/PhpWriter.html
```
Difference is in `/` or `.` in namespace names and URL.

**Comment by dg** [comment]
Fixed
