### ISSUE TITLE
Add GitHub Actions in docs

### ISSUE THREAD

**Issue by petrparolek** [nette/docs#873]
It would nice add GA simple tutorial, if there is Travis CI.

**Comment by dg** [comment]
?

**Comment by petrparolek** [comment]
idea write in in docs about GitHub Actions

**Comment by dg** [comment]
How is this related to Nette?

**Comment by petrparolek** [comment]
Same as Travis CI.

**Comment by dg** [comment]
You mean, like, doc for Nette Tester? 

Strašně nenávidím tahat z někoho každé slovo 😡

**Comment by petrparolek** [comment]
promin, nenapsal jsem, že jde o tester.

**Comment by dg** [comment]
Nenapsal jsi vůbec nic. Sorry, ale to je jak hadrem přes hubu. Si myslíš, že prdneš do issues „Travis CI -> Github actions“ bez jediného slova někdo se sebere a půjde ti splnit přání???

Hovno. Tak to napiš. Vem si to za úkol. Předělej tutoriál a neponižuj ostatní tímto způsobem.

**Comment by petrparolek** [comment]
to není myšleno jako automat! Ale pouze nápad! BTW. vurgarismy si nepomůžeš.

**Comment by dg** [comment]
Ale ano, vulgarismy si ulevím, když mě někdo nasere. Příště prosím dej do sepsání issue alespoň trošku úsilí, ať tím nikoho nevytáčíš. Já to tady smažu a když ten návod na Actions vytvoříš, pošli PR, bude to super.

**Comment by petrparolek** [comment]
👍
