### ISSUE TITLE
Travis -> GitHub Actions

### ISSUE THREAD

**Issue by petrparolek** [nette/docs#876]
Bylo by fajn přepsat https://tester.nette.org/cs/testing-with-travis na GitHub Actions

**Comment by milo** [comment]
Spíš doplnit. Pošleš PR?

**Comment by petrparolek** [comment]
Přemýšlel jsem nad tím, ale mám povcit, že nemám tak dobré znalosti GA, vždycky jsem použi kusl kudu yaml konfigurace a poupravil. Myslím si, že metoda pokus / omyl a copy % paste není dobráý nápad  i do dokumentace.

**Comment by milo** [comment]
Ale někdo to zanalyzovat a vysvětlit musí.

**Comment by petrparolek** [comment]
někdo zběhlý, pro GitLab CI bycch člíánek napsal v pohodě, jednoduchá a srozumitelná konfigurace

**Comment by petrparolek** [comment]
mám si troufnout? Není tu nějaký profesionál DevOps? Nebo máš na mysli GitLab?

**Comment by petrparolek** [comment]
inspiraci bych vzal tu https://archiv.pehapkari.cz/blog/2017/03/30/nastaveni-gitlab-ci-pro-produkcni-aplikaci/ , snad plagiátorství může být, když nejsem na VŠ.

**Comment by dg** [comment]
Tak GitLab jsem nikdy neviděl a o GA víme všichni stejné málo. Takže jsi vlastně profesionál :)

**Comment by dg** [comment]
@petrparolek ping
