### ISSUE TITLE
[Latte] Add {block |filter} and {= |filter} to Syntax > Filters overview

### ISSUE THREAD

**Issue by dakur** [nette/docs#901]
When I was searching for an answer to [this tread](https://forum.nette.org/en/34614-remove-whitespace-around-tag-content#p216612), [Syntax > Filters](https://latte.nette.org/en/syntax#toc-filters) was exactly the place I clicked through navigation to search for it there. But it wasn't there, I had to pick it up from examples of filters.

**Comment by dg** [comment]
Can you send PR?

**Comment by dakur** [comment]
Not now, otherwise I would. Maybe at the end of July, but can't say now.

**Comment by dg** [comment]
OK, there's no hurry.

**Comment by dakur** [comment]
Finally, I found some time even earlier. 👉 #902
