### ISSUE TITLE
Older docs on https://doc.nette.org

### ISSUE THREAD

**Issue by petrparolek** [nette/docs#926]
Version: 2.4 - 3.0

Older docs is missing.

**Comment by dg** [comment]
For most sites, the switch to 2.4 should be available. The 3.0 is temporary unavailable.

**Comment by dg** [comment]
![10EACBA9-84C7-46A0-B091-037E91AA0414](https://user-images.githubusercontent.com/194960/147830068-af0e006b-e370-4ae6-8f3b-057cbea769e0.jpeg)

**Comment by petrparolek** [comment]
Již funguje
