### ISSUE TITLE
Tracy Scrubber is missing in docs

### ISSUE THREAD

**Issue by petrparolek** [nette/docs#949]
ref https://github.com/nette/tracy/pull/439/

**Comment by dg** [comment]
Send PR please

**Comment by petrparolek** [comment]
cc @dakujem

**Comment by dakujem** [comment]
Point me to the place the doc is needed and I'll add it there. I can't write Czech reliably though.

**Comment by petrparolek** [comment]
You can write in English and we will translate to Czech.

**Comment by dakujem** [comment]
But where to put the docs? I did not find tracy mentioned in nette docs.

For now I created this: https://github.com/nette/tracy/pull/548
