### ISSUE TITLE
Latte include docs could mention `block` syntax

### ISSUE THREAD

**Issue by helvete** [nette/docs#954]
The Latte [documentation page](https://latte.nette.org/cs/tags#toc-include) for `include` tag does not mention `include block` syntax.

It would be beneficial if it does, as one could not use dynamic name resolution w/o the `block` argument.

To be specific, this for example does not work:
```latte
{include $dynamicName from './subtemplate.latte', varName: $varValue}
```
But this does:
```latte
{include block $dynamicName from './subtemplate.latte', varName: $varValue}
```
I understand the difference between these (now :-) ) - the former includes a template while the latter includes a block from a template.

I believe having the difference mentioned within the docs will improve understanding of the behaviour.

More on this topic to be found in related [nette forum thread](https://forum.nette.org/en/35384-dynamic-include-macro-name).

**Comment by dg** [comment]
Feel free to send PR.

**Comment by dg** [comment]
@helvete  Actually, I wonder why you didn't add that to the documentation? What's the barrier?

**Comment by helvete** [comment]
Hell I could have. The reason I haven't done that is that I totally forgot about this. 

I can see [the documentation](https://latte.nette.org/cs/template-inheritance#toc-vykresleni-bloku) has already been updated, so thank you!
