### ISSUE TITLE
Version switch is almost invisible

### ISSUE THREAD

**Issue by mabar** [nette/docs#957]
Currently version switch in docs is really small and looks like a part of path to page. It would be great to make it easier to find - maybe a box, different color, bit bigger? Thank you

![image](https://user-images.githubusercontent.com/20974277/194414297-b8dced8c-af0e-444e-8c67-2eedd243cbc0.png)
![image](https://user-images.githubusercontent.com/20974277/194414845-6011a75a-caa5-46f9-a4f1-9614c4bbd92e.png)

**Comment by eydun** [comment]
Thanks, I have often been searching for that 😁

**Comment by dg** [comment]
fixed
