### ISSUE TITLE
Invalid SSL certificate

### ISSUE THREAD

**Issue by valenjeb** [nette/docs#965]
The browser blocks assets (scripts, styles, and images) because of an SSL issue.

URL: https://latte.nette.org/en/

**Comment by milo** [comment]
I don't see any problem. Do you have the correct OS time? Could you send a screenshot?

**Comment by valenjeb** [comment]
@milo, it seems to be ok right now. It was like two or three days that I couldn't load the website properly. Maybe it was something on my end. I'm not sure..
Anyway, thank you for the response.
